model:
  type: diffusion # dsm and diffusion
  network: MGDMFullDP
  hidden_dim: 256
  num_convs: 6
  num_convs_local: 6
  cutoff: 1.5
  mlp_act: relu
  beta_schedule: sigmoid
  beta_start: 1.e-7
  beta_end: 2.e-3
  num_diffusion_timesteps: 1000
  edge_order: 3
  edge_encoder: mlp
  smooth_conv: false
  num_layer: 9
  feats_dim: 5
  soft_edge: True
  norm_coors: True
  m_dim: 128
  context: None
#  context: ['homo']
  vae_context: False
  num_atom: 6

train:
  seed: 2021
  batch_size: 128
  val_freq: 100
  max_iters: 500
  max_grad_norm: 10.0
  num_workers: 4
  anneal_power: 2.0
  optimizer:
    type: adam
    lr: 1.e-4
    weight_decay: 0.
    beta1: 0.95
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.6
    patience: 10
    min_lr: 1.e-5
  transform:
    mask:
      type: mixed
      min_ratio: 0.0
      max_ratio: 1.2
      min_num_masked: 1
      min_num_unmasked: 0
      p_random: 0.5
      p_bfs: 0.25
      p_invbfs: 0.25
    contrastive:
      num_real: 50
      num_fake: 50
      pos_real_std: 0.05
      pos_fake_std: 2.0

dataset:
  train: ./data/GEOM/QM9/train_data_40k.pkl
  val: ./data/GEOM/QM9/val_data_5k.pkl
  test: ./data/GEOM/QM9/test_data_1k.pkl

